name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: snyk/actions/setup@master
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: "Snyk library issue test"
        run: snyk test --all-projects --reachable || true 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: "Snyk library issues to snyk.io"
        run: snyk monitor --all-projects --reachable || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: "Snyk code scan test"
        run: snyk code test || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
